### ISSUE TITLE
Run on Jetson Nano got error

### ISSUE THREAD

**Issue by gogo000** [rbonghi/jetson_stats#11]
sudo jtop --debug
Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jtop/__main__.py", line 152, in main
    curses.wrapper(gui, args, tegra)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/jtop/__main__.py", line 98, in gui
    pages.draw(stat)
  File "/usr/local/lib/python2.7/dist-packages/jtop/jtopgui.py", line 173, in draw
    page(self.stdscr, stat)
  File "/usr/local/lib/python2.7/dist-packages/jtop/jtopgui.py", line 99, in all_info
    line_counter = plot_CPUs(stdscr, line_counter, jetsonstats['CPU'], width)
  File "/usr/local/lib/python2.7/dist-packages/jtop/jtopguilib.py", line 135, in plot_CPUs
    linear_percent_gauge(stdscr, gauge, max_bar, offest + off_idx, start)
  File "/usr/local/lib/python2.7/dist-packages/jtop/jtopguilib.py", line 115, in linear_percent_gauge
    stdscr.addstr(offset, start + 6 + size_bar - len(grey_part), grey_part, curses.A_DIM)
_curses.error: addstr() returned ERR

**Comment by rbonghi** [comment]
Hi @gogo000 ,

This is a know bug, I will fix in the next release.
The size of your shell is too much little, use a resolution bigger.

**Comment by rbonghi** [comment]
Added Warning screen for size too much small.

![image](https://user-images.githubusercontent.com/4551246/58884180-2ef33d80-86e0-11e9-80cb-0eb8e86c9fb3.png)

The new release is coming soon
