### ISSUE TITLE
Exception in jtop.service

### ISSUE THREAD

**Issue by vividy163** [rbonghi/jetson_stats#163]
I run latest 3.1.0 on my jetson. but the following exception occurs sometimes, and result service shutdown.
```
[INFO] jtop.service - tegrastats close
[ERROR] jtop.service - Error subprocess PyMemoryView_FromBuffer(): info->buf must not be NULL
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jtop/service.py", line 191, in run
    control = self.q.get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jtop/service.py", line 278, in run
    self.jetson_clocks.stop()
  File "/usr/local/lib/python3.6/dist-packages/jtop/core/jetson_clocks.py", line 435, in stop
    self._error_status()
  File "/usr/local/lib/python3.6/dist-packages/jtop/core/jetson_clocks.py", line 456, in _error_status
    raise ex_value
  File "/usr/local/lib/python3.6/dist-packages/jtop/core/jetson_clocks.py", line 398, in _th_show
    lines = cmd(timeout=COMMAND_TIMEOUT)
  File "/usr/local/lib/python3.6/dist-packages/jtop/core/command.py", line 108, in __call__
    raise ex_value
  File "/usr/local/lib/python3.6/dist-packages/jtop/core/command.py", line 78, in target
    for line in iter(self.process.stdout.readline, b''):
ValueError: PyMemoryView_FromBuffer(): info->buf must not be NULL
[INFO] jtop.service - Force tegrastats close
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle traceback objects
[INFO] jtop.service - Service closed
```

**Comment by rbonghi** [comment]
If this error appear again please open this issue
