### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by jungyin** [rbonghi/jetson_stats#179]
When I try to update the Jetson stats on the Jetson nano, I will be prompted with an error when using jtop, ModuleNotFoundError: no module named '_ What should I do

error logs:
Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 5, in <module>
    from jtop.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/jtop/__main__.py", line 24, in <module>
    import curses
  File "/usr/local/lib/python3.6/curses/__init__.py", line 16, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by huajng** [comment]
I meet the same issue, and how to solve it?

**Comment by rbonghi** [comment]
Hi all,
Can you explain a bit more about the type of issue? I'm using a Nano and I didn't see this bug.

Are you using a specific configuration?
