### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'NV Power Mode: 5W'

### ISSUE THREAD

**Issue by dosvidos** [rbonghi/jetson_stats#24]
Can't run **jtop** on Jetson Nano running  L4T 32.2 from JetPack 4.2.1

**sudo jtop** fails with an error:
Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 108, in main
    with jtop(interval=args.refresh) as jetson:
  File "/usr/local/lib/python3.6/dist-packages/jtop/jtop.py", line 76, in __init__
    self.nvp = NVPmodel(os.environ["JETSON_TYPE"], jetson_clocks=self.jc)
  File "/usr/local/lib/python3.6/dist-packages/jtop/core/nvpmodel.py", line 102, in __init__
    self.update()
  File "/usr/local/lib/python3.6/dist-packages/jtop/core/nvpmodel.py", line 155, in update
    self.num = int(lines[1])
ValueError: invalid literal for int() with base 10: 'NV Power Mode: 5W'

I've installed [jetson-stats-1.7.3.tar.gz](https://files.pythonhosted.org/packages/62/6f/a2fcd866a3ca4e94a81cf9a34e144901ef6356225bbab7d919fd1137eff7/jetson-stats-1.7.3.tar.gz) using **pip**
The kernel is 4.9.140-tegra

**Comment by rbonghi** [comment]
Hi @dosvidos ,

I think the error is in [jetson_variables](https://github.com/rbonghi/jetson_stats/blob/master/scripts/jetson_variables). I not set the new reference for the JetPack 4.2.1

I will add today or for the end of this week. :-)
