### ISSUE TITLE
Nvidia Jetson Xavier NX Jetpack 5.0.1 Jetson-Stats dosnt start ERROR

### ISSUE THREAD

**Issue by Matt-dere** [rbonghi/jetson_stats#258]
Hello there, 

after the installation, jetson-stats dosnt start.

jtop
Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jtop/__main__.py", line 146, in main
    with jtop(interval=interval) as jetson:
  File "/usr/local/lib/python2.7/dist-packages/jtop/jtop.py", line 1081, in __enter__
    self.start()
  File "/usr/local/lib/python2.7/dist-packages/jtop/jtop.py", line 956, in start
    init = self._get_configuration()
  File "/usr/local/lib/python2.7/dist-packages/jtop/jtop.py", line 907, in _get_configuration
    data = self._controller.get(self._interval * TIMEOUT_GAIN)
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer

**Comment by rbonghi** [comment]
This error should now be fixed with the latest release **4.0** try to install and check again
```
sudo -H pip install -U jetson-stats
```
