### ISSUE TITLE
[4.1.5] GUI crashes when showing INFO tab on reduced mode

### ISSUE THREAD

**Issue by SolaZn** [rbonghi/jetson_stats#375]
Hello again @rbonghi !

**Describe the bug**
GUI crashes when trying to show INFO tab while using reduced terminal
GUI closes down immediately while switching to INFO tab or when INFO tab is reduced
`Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 151, in main
    loop=args.loop, seconds=LOOP_SECONDS, color_filter=color_filter)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/jtop/gui/jtopgui.py", line 114, in __init__
    self.run(loop, seconds)
  File "/usr/local/lib/python3.6/dist-packages/jtop/gui/jtopgui.py", line 143, in run
    self.draw()
  File "/usr/local/lib/python3.6/dist-packages/jtop/gui/lib/common.py", line 80, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jtop/gui/jtopgui.py", line 158, in draw
    page.draw(self.key, self.mouse)
  File "/usr/local/lib/python3.6/dist-packages/jtop/gui/pinfo.py", line 89, in draw
    interfaces_size_y, interfaces_size_x = plot_dictionary(self.stdscr, start_pos + hardware_size_y + 2, 2 + max_size_x, 'Interfaces', interfaces)
  File "/usr/local/lib/python3.6/dist-packages/jtop/gui/lib/common.py", line 173, in plot_dictionary
    stdscr.addstr(pos_y + idx + 1, pos_x + 1, str(name) + ":", curses.A_BOLD)
_curses.error: addwstr() returned ERR
`

**To Reproduce**

Open jtop GUI and go to the INFO tab
Try to reduce the size of the terminal

**Additional context**

Model: NVIDIA Jetson Nano Developer Kit - Jetpack 4.6 [L4T 32.6.1]
NV Power Mode: MAXN - Type: 0
Hardware:
 - BoardIDs: p3448
 - Module: Not available
 - SoC: tegra210
 - CUDA Arch BIN: 5.3
 - Codename: Porg
 - Serial Number: 1421621008821
Platform:
 - Machine: aarch64
 - System: Linux
 - Distribution: Ubuntu 18.04 Bionic Beaver
 - Release: 4.9.253-tegra
 - Python: 3.6.9
jtop:
 - Version: 4.1.5
 - Service: Active

Thank you very much !

**Comment by rbonghi** [comment]
I think there is a bug on this page. I will take a look and fix it!

Meanwhile, if you enlarge your terminal should be fixed.
