### ISSUE TITLE
unbound local error

### ISSUE THREAD

**Issue by LMSAas** [rbonghi/jetson_stats#42]
jtop fails to start on nvidia TX2.
installed via `sudo -H pip3 install jetson-stats`

`➜  ~ sudo jtop
Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jtop/__main__.py", line 64, in main
    curses.wrapper(JTOPGUI, args.refresh, jetson, [ALL, GPU, CTRL, INFO], init_page=args.page)
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/jtop/gui/jtopgui.py", line 78, in __init__
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/jtop/gui/jtopgui.py", line 99, in run
    self.draw()
  File "/usr/local/lib/python3.5/dist-packages/jtop/gui/jtopguilib.py", line 71, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jtop/gui/jtopgui.py", line 110, in draw
    page.draw(self.key)
  File "/usr/local/lib/python3.5/dist-packages/jtop/gui/pall.py", line 43, in draw
    line_counter = plot_CPUs(self.stdscr, line_counter, self.jetson.stats['CPU'], width)
  File "/usr/local/lib/python3.5/dist-packages/jtop/gui/jtopguilib.py", line 107, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jtop/gui/jtopguimenu.py", line 48, in plot_CPUs
    return int(offest + idx + 1)
UnboundLocalError: local variable 'idx' referenced before assignment
`

**Comment by rbonghi** [comment]
Hi @LMSAas ,

I just check on my TX2, but I don't have this error, can you give more information?
