### ISSUE TITLE
Missing "," in os.symlink call

### ISSUE THREAD

**Issue by albertfaromatics** [rbonghi/jetson_stats#439]
## Describe the bug

I think there's a missing "," in the call here:

https://github.com/rbonghi/jetson_stats/blob/98a6d1b7547b3842d0b921efbf9d3398e35335bf/jtop/jetson_config.py#L131

Found it when running jetson_config to set to boot to CLI directly with no desktop

## To Reproduce

1. run sudo jetson_config
2. Go to Desktop
3. Select B1
4. Error pops out: 

`Traceback (most recent call last):
  File "/usr/local/bin/jetson_config", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/jtop/jetson_config.py", line 238, in main
    curses.wrapper(JTOPCONFIG, MAIN_PAGE)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/jtop/gui/jtopguiconfig.py", line 74, in __init__
    self.loop()
  File "/usr/local/lib/python3.8/dist-packages/jtop/gui/jtopguiconfig.py", line 154, in loop
    while not self.events():
  File "/usr/local/lib/python3.8/dist-packages/jtop/gui/jtopguiconfig.py", line 167, in events
    status_keyboard = self.keyboard(event)
  File "/usr/local/lib/python3.8/dist-packages/jtop/gui/jtopguiconfig.py", line 201, in keyboard
    output = cmd()
  File "/usr/local/lib/python3.8/dist-packages/jtop/jetson_config.py", line 131, in desktop_set_B1
    os.symlink('/lib/systemd/system/getty@.service' '/etc/systemd/system/getty.target.wants/getty@tty1.service')
TypeError: symlink() missing required argument 'dst' (pos 2)`

### Board

Software part of jetson-stats 4.2.2 - (c) 2023, Raffaello Bonghi
Jetpack missing!
 - Model: NVIDIA Jetson Xavier NX Developer Kit
 - L4T: 35.4.1
NV Power Mode[8]: MODE_20W_6CORE
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - 699-level Part Number: 699-13668-0003-301 B.0
 - P-Number: p3668-0003
 - Module: NVIDIA Jetson Xavier NX (16GB ram)
 - SoC: tegra194
 - CUDA Arch BIN: 7.2
 - Codename: Jakku
Platform:
 - Machine: aarch64
 - System: Linux
 - Distribution: Ubuntu 20.04 focal
 - Release: 5.10.120-tegra
 - Python: 3.8.10
jtop:
 - Version: 4.2.2
 - Service: Inactive
Libraries:
 - CUDA: 12.2.128
 - cuDNN: 8.6.0.166
 - TensorRT: 5.1.2
 - VPI: 2.3.9
 - Vulkan: 1.3.204
 - OpenCV: 4.7.0 - with CUDA: YES

**Comment by 4dec** [comment]
Ran into the same issue, and I confirmed with local mods that the os.symlink call is the culprit.  I can fix, look for a PR shortly.

**Comment by rbonghi** [comment]
Fixed on new jetson-stats release 4.2.4. Please update

```
sudo pip3 install -U jetson-stats
```
