### ISSUE TITLE
Error on jetson nano

### ISSUE THREAD

**Issue by sushruth13** [rbonghi/jetson_stats#496]
## Describe the bug
Jtop does not start, I cant restart the service. Everytime  I restart the service, the service exits in a few minutes

## Screenshots
these are the journal logs
Feb 27 13:26:35 jet6b-desktop systemd[1]: Started jtop service.
Feb 27 13:26:35 jet6b-desktop jtop[5814]: [INFO] jtop.service - jetson_stats 4.2.6 - server loaded
Feb 27 13:26:35 jet6b-desktop jtop[5814]: [INFO] jtop.service - Running on Python: 3.6.9
Feb 27 13:26:35 jet6b-desktop jtop[5814]: [INFO] jtop.core.hardware - Hardware detected aarch64
Feb 27 13:26:35 jet6b-desktop jtop[5814]: Skip for setup.py
Feb 27 13:26:35 jet6b-desktop jtop[5814]: Traceback (most recent call last):
Feb 27 13:26:35 jet6b-desktop jtop[5814]:   File "/usr/local/bin/jtop", line 8, in <module>
Feb 27 13:26:35 jet6b-desktop jtop[5814]:     sys.exit(main())
Feb 27 13:26:35 jet6b-desktop jtop[5814]:   File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 104, in main
Feb 27 13:26:35 jet6b-desktop jtop[5814]:     server = JtopServer(force=args.force)
Feb 27 13:26:35 jet6b-desktop jtop[5814]:   File "/usr/local/lib/python3.6/dist-packages/jtop/service.py", line 281, in __init__
Feb 27 13:26:35 jet6b-desktop jtop[5814]:     self.board = {'hardware': get_hardware()}
Feb 27 13:26:35 jet6b-desktop jtop[5814]:   File "/usr/local/lib/python3.6/dist-packages/jtop/core/hardware.py", line 71, in get_hardware
Feb 27 13:26:35 jet6b-desktop jtop[5814]:     jetson = get_jetson_variables()
Feb 27 13:26:35 jet6b-desktop jtop[5814]:   File "/usr/local/lib/python3.6/dist-packages/jtop/core/jetson_variables.py", line 301, in get_jetson_variables
Feb 27 13:26:35 jet6b-desktop jtop[5814]:     part_number, jetson_part_number = get_part_number()
Feb 27 13:26:35 jet6b-desktop jtop[5814]:   File "/usr/local/lib/python3.6/dist-packages/jtop/core/jetson_variables.py", line 277, in get_part_number
Feb 27 13:26:35 jet6b-desktop jtop[5814]:     bus = SMBus(bus_number, force=True)
Feb 27 13:26:35 jet6b-desktop jtop[5814]: NameError: name 'SMBus' is not defined
Feb 27 13:26:35 jet6b-desktop systemd[1]: jtop.service: Main process exited, code=exited, status=1/FAILURE
Feb 27 13:26:35 jet6b-desktop systemd[1]: jtop.service: Failed with result 'exit-code'.
Feb 27 13:26:43 jet6b-desktop systemd[1]: jtop.service: Service hold-off time over, scheduling restart.
Feb 27 13:26:43 jet6b-desktop systemd[1]: jtop.service: Failed to schedule restart job: Unit jtop.service not found.
Feb 27 13:26:43 jet6b-desktop systemd[1]: jtop.service: Failed with result 'exit-code'.

### Board

Output from `jetson_release -v`:

* jetson-stats version: [e.g. 1.8]
* P-Number: [e.g. pXXXX-XXXX]
* Module: [e.g. NVIDIA Jetson XXX]
* Jetpack: [e.g. 4.3]
* L4T: [e.g. 5.2.1]

### Log from jtop.service

Attach here the output from: `journalctl -u jtop.service -n 100 --no-pager`

### Log from jetson-stats installation

Attach here the output from: `sudo -H pip3 install --no-cache-dir -v -U jetson-stats`

### RAW Data

File from `jtop --error-log` attached

**Comment by rbonghi** [comment]
Hi @sushruth13 

Can you please try installing smbus using this command and then reboot the jtop service?

```
sudo pip3 install smbus2
```
