### ISSUE TITLE
KeyError: Memory

### ISSUE THREAD

**Issue by yanghengyii** [rbonghi/jetson_stats#528]
I tried to install jetson-stats 4.2.8 on jetson Xavier NX. An error occurs when I input `jtop`. 
`Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jtop/__main__.py", line 147, in main
    with jtop(interval=interval) as jetson:
  File "/usr/local/lib/python3.6/dist-packages/jtop/jtop.py", line 1277, in __enter__
    self.start()
  File "/usr/local/lib/python3.6/dist-packages/jtop/jtop.py", line 1157, in start
    self._memory._initialize(self._controller, init['memory'])
KeyError: 'memory'
`
However, when I install jetson-stats 4.1.5. It works on board but turns out that CUDA is missing.

**Comment by yanghengyii** [comment]
version 4.2.4 works.
<img width="735" alt="image" src="https://github.com/rbonghi/jetson_stats/assets/82561314/4df55515-cf69-444a-8dae-1188419e3de7">
