### ISSUE TITLE
missing key freq and crash

### ISSUE THREAD

**Issue by rbonghi** [rbonghi/jetson_stats#556]
Key error on Freq CPU

Forum post: https://forums.developer.nvidia.com/t/orin-nx-jtop-read-cpu-crash/301611

![image](https://github.com/user-attachments/assets/14e52fed-6f91-49fc-87a4-ea9e886b1ca9)

**Comment by soyszala** [comment]
Experienced the same issue, I'll post some details here in case you would find any information useful.

## Describe the bug

Jtop crashes when trying to check CPU information (switching to CPU tab)

## To Reproduce

1. Run `jtop` command
2. Press key 3

## Additional context

Always reproducible. Recently switched to new board and new Jetpack version (see below), didn't experience the issue before.

Traceback from the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/jtop/__main__.py", line 160, in main
    curses.wrapper(JTOPGUI, jetson, pages, init_page=args.page,
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/jtop/gui/jtopgui.py", line 100, in __init__
    self.run(loop, seconds)
  File "/usr/local/lib/python3.10/dist-packages/jtop/gui/jtopgui.py", line 129, in run
    self.draw()
  File "/usr/local/lib/python3.10/dist-packages/jtop/gui/jtopgui.py", line 143, in draw
    page.draw(self.key, self.mouse)
  File "/usr/local/lib/python3.10/dist-packages/jtop/gui/pcpu.py", line 138, in draw
    step_height, step_width, size_columns, size_rows = cpu_grid(
  File "/usr/local/lib/python3.10/dist-packages/jtop/gui/pcpu.py", line 78, in cpu_grid
    print_cpu(stdscr, idx, cpu, start_y + idx_row * step_height, start_x + idx_column * step_width, step_height - 1, step_width - 1)
  File "/usr/local/lib/python3.10/dist-packages/jtop/gui/pcpu.py", line 122, in print_cpu
    freq = cpu['freq']
KeyError: 'freq'
```

### Board


* jetson-stats version: 4.2.9
* P-Number: p3767-0000
* Module: NVIDIA Jetson Orin NX (16GB ram)
* Jetpack: 6.0
* L4T: 36.3.0

### Log from jtop.service

Error after `Aug 05 09:32:14` multiple times
<details>
<summary>LOG</summary>

```
Aug 05 09:32:08 tegra-ubuntu systemd[1]: Started jtop service.
Aug 05 09:32:08 tegra-ubuntu jtop[5921]: [INFO] jtop.service - jetson_stats 4.2.9 - server loaded
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.service - Running on Python: 3.10.12
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.hardware - Hardware detected aarch64
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.hardware - NVIDIA Jetson 699-level Part Number=699-13767-0000-300 M.1
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.hardware - NVIDIA Jetson Module=NVIDIA Jetson Orin NX (16GB ram)
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.hardware - NVIDIA Jetson detected L4T=36.3.0
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.cpu - Found 8 CPU
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.gpu - GPU "gpu" status in /sys/devices/platform/bus@0/17000000.gpu
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.gpu - GPU "gpu" frq in /sys/devices/platform/bus@0/17000000.gpu/devfreq/17000000.gpu
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.gpu - NVIDIA SMI exist!
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.processes - Process service started
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.memory - Found EMC!
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.memory - Memory service started
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.engine - Special Engine group found: [dlaX]
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.engine - Special Engine group found: [pvaX]
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.engine - Engines found: [APE DLA0 DLA1 NVDEC NVENC NVJPG OFA PVA0 SE VIC]
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.temperature - Found thermal "cv0" in thermal_zone2
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.temperature - Found thermal "cpu" in thermal_zone0
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.temperature - Found thermal "soc2" in thermal_zone7
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.temperature - Found thermal "soc0" in thermal_zone5
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.temperature - Found thermal "cv1" in thermal_zone3
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.temperature - Found thermal "gpu" in thermal_zone1
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.temperature - Found thermal "tj" in thermal_zone8
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.temperature - Found thermal "soc1" in thermal_zone6
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.temperature - Found thermal "cv2" in thermal_zone4
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.power - Alarms VDD_IN - {'crit_alarm': 0, 'max_alarm': 0}
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.power - Alarms VDD_CPU_GPU_CV - {'crit_alarm': 0, 'max_alarm': 0}
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.power - Alarms VDD_SOC - {'crit_alarm': 0, 'max_alarm': 0}
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [WARNING] jtop.core.power - Skipped "sum of shunt voltages" /sys/bus/i2c/devices/1-0040/hwmon/hwmon2/in7_label
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.power - Found I2C power monitor
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [WARNING] jtop.core.power - Skipped usb-charger type=USB in=usb-charger
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.fan - Fan pwmfan(1) found in /sys/class/hwmon/hwmon1
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.fan - RPM pwm_tach found in /sys/class/hwmon/hwmon3
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.fan - Found nvfancontrol.service
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.jetson_clocks - jetson_clocks found in /usr/bin/jetson_clocks
Aug 05 09:32:09 tegra-ubuntu jtop[5921]: [INFO] jtop.core.nvpmodel - nvpmodel running in [2]15W - Default: 2
Aug 05 09:32:09 tegra-ubuntu jtop[5941]: [INFO] jtop.service - Initialization service
Aug 05 09:32:09 tegra-ubuntu jtop[5941]: [INFO] jtop.service - service ready
Aug 05 09:32:14 tegra-ubuntu jtop[5941]: [INFO] jtop.service - jtop timer thread started 1000ms
Aug 05 09:32:20 tegra-ubuntu jtop[5941]: [INFO] jtop.service - jtop timer thread close
Aug 05 09:32:24 tegra-ubuntu jtop[5941]: [INFO] jtop.service - jtop timer thread started 1000ms
Aug 05 09:32:36 tegra-ubuntu jtop[5941]: [INFO] jtop.service - jtop timer thread close
Aug 05 09:33:08 tegra-ubuntu jtop[5941]: [INFO] jtop.service - jtop timer thread started 1000ms
Aug 05 09:34:55 tegra-ubuntu jtop[5941]: [INFO] jtop.service - jtop timer thread close
Aug 05 09:36:41 tegra-ubuntu jtop[5941]: [INFO] jtop.service - jtop timer thread started 1000ms
```

</details>

### Log from jetson-stats installation

<details>
<summary>LOG</summary>

```
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
Collecting jetson-stats
  Downloading jetson-stats-4.2.9.tar.gz (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.6/116.6 KB 2.2 MB/s eta 0:00:00
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-7aavfqq1/jetson_stats.egg-info
  writing /tmp/pip-pip-egg-info-7aavfqq1/jetson_stats.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-7aavfqq1/jetson_stats.egg-info/dependency_links.txt
  writing entry points to /tmp/pip-pip-egg-info-7aavfqq1/jetson_stats.egg-info/entry_points.txt
  writing requirements to /tmp/pip-pip-egg-info-7aavfqq1/jetson_stats.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-7aavfqq1/jetson_stats.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-7aavfqq1/jetson_stats.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-7aavfqq1/jetson_stats.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files found matching 'Dockerfile'
  warning: no previously-included files found matching '.dockerignore'
  no previously-included directories found matching 'tests'
  no previously-included directories found matching 'docs'
  no previously-included directories found matching 'examples'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-7aavfqq1/jetson_stats.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Requirement already satisfied: distro in /usr/lib/python3/dist-packages (from jetson-stats) (1.7.0)
Requirement already satisfied: smbus2 in /usr/local/lib/python3.10/dist-packages (from jetson-stats) (0.4.3)
Building wheels for collected packages: jetson-stats
  Running command python setup.py bdist_wheel
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/jtop
  copying jtop/jtop.py -> build/lib/jtop
  copying jtop/jetson_swap.py -> build/lib/jtop
  copying jtop/__main__.py -> build/lib/jtop
  copying jtop/__init__.py -> build/lib/jtop
  copying jtop/terminal_colors.py -> build/lib/jtop
  copying jtop/service.py -> build/lib/jtop
  copying jtop/jetson_config.py -> build/lib/jtop
  copying jtop/jetson_release.py -> build/lib/jtop
  copying jtop/github.py -> build/lib/jtop
  creating build/lib/jtop/gui
  copying jtop/gui/pcpu.py -> build/lib/jtop/gui
  copying jtop/gui/jtopguiconfig.py -> build/lib/jtop/gui
  copying jtop/gui/jtopgui.py -> build/lib/jtop/gui
  copying jtop/gui/pmem.py -> build/lib/jtop/gui
  copying jtop/gui/__init__.py -> build/lib/jtop/gui
  copying jtop/gui/pcontrol.py -> build/lib/jtop/gui
  copying jtop/gui/pengine.py -> build/lib/jtop/gui
  copying jtop/gui/pinfo.py -> build/lib/jtop/gui
  copying jtop/gui/pgpu.py -> build/lib/jtop/gui
  copying jtop/gui/pall.py -> build/lib/jtop/gui
  creating build/lib/jtop/core
  copying jtop/core/memory.py -> build/lib/jtop/core
  copying jtop/core/temperature.py -> build/lib/jtop/core
  copying jtop/core/power.py -> build/lib/jtop/core
  copying jtop/core/timer_reader.py -> build/lib/jtop/core
  copying jtop/core/tegra_parse.py -> build/lib/jtop/core
  copying jtop/core/engine.py -> build/lib/jtop/core
  copying jtop/core/exceptions.py -> build/lib/jtop/core
  copying jtop/core/fan.py -> build/lib/jtop/core
  copying jtop/core/__init__.py -> build/lib/jtop/core
  copying jtop/core/processes.py -> build/lib/jtop/core
  copying jtop/core/command.py -> build/lib/jtop/core
  copying jtop/core/jetson_variables.py -> build/lib/jtop/core
  copying jtop/core/nvpmodel.py -> build/lib/jtop/core
  copying jtop/core/jetson_clocks.py -> build/lib/jtop/core
  copying jtop/core/hardware.py -> build/lib/jtop/core
  copying jtop/core/common.py -> build/lib/jtop/core
  copying jtop/core/tegrastats.py -> build/lib/jtop/core
  copying jtop/core/config.py -> build/lib/jtop/core
  copying jtop/core/gpu.py -> build/lib/jtop/core
  copying jtop/core/jetson_libraries.py -> build/lib/jtop/core
  copying jtop/core/cpu.py -> build/lib/jtop/core
  creating build/lib/jtop/gui/lib
  copying jtop/gui/lib/chart.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/colors.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/__init__.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/process_table.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/common.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/linear_gauge.py -> build/lib/jtop/gui/lib
  copying jtop/gui/lib/smallbutton.py -> build/lib/jtop/gui/lib
  /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  installing to build/bdist.linux-aarch64/wheel
  running install
  Install status:
   - [X] super_user
   - [ ] virtualenv
   - [ ] docker
  ERROR:jtop.service:Does not exist jetson_stats
  INFO:jtop.service:Found jtop.service
  INFO:jtop.service: - STOP jtop.service
  INFO:jtop.service: - DISABLE jtop.service
  Removed /etc/systemd/system/multi-user.target.wants/jtop.service.
  INFO:jtop.service: - REMOVE jtop.service from /etc/systemd/system
  INFO:jtop.service: - Reload all daemons
  INFO:jtop.core.jetson_variables:Found jtop_env.sh
  INFO:jtop.core.jetson_variables: - Remove jtop_env.sh from /etc/profile.d/
  running install_lib
  creating build/bdist.linux-aarch64
  creating build/bdist.linux-aarch64/wheel
  creating build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/jtop.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/jetson_swap.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/__main__.py -> build/bdist.linux-aarch64/wheel/jtop
  creating build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pcpu.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/jtopguiconfig.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/jtopgui.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pmem.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/__init__.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pcontrol.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  creating build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/chart.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/colors.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/__init__.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/process_table.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/common.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/linear_gauge.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/lib/smallbutton.py -> build/bdist.linux-aarch64/wheel/jtop/gui/lib
  copying build/lib/jtop/gui/pengine.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pinfo.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pgpu.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  copying build/lib/jtop/gui/pall.py -> build/bdist.linux-aarch64/wheel/jtop/gui
  creating build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/memory.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/temperature.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/power.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/timer_reader.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/tegra_parse.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/engine.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/exceptions.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/fan.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/__init__.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/processes.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/command.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/jetson_variables.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/nvpmodel.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/jetson_clocks.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/hardware.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/common.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/tegrastats.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/config.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/gpu.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/jetson_libraries.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/core/cpu.py -> build/bdist.linux-aarch64/wheel/jtop/core
  copying build/lib/jtop/__init__.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/terminal_colors.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/service.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/jetson_config.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/jetson_release.py -> build/bdist.linux-aarch64/wheel/jtop
  copying build/lib/jtop/github.py -> build/bdist.linux-aarch64/wheel/jtop
  running install_data
  creating build/bdist.linux-aarch64/wheel/jetson_stats-4.2.9.data
  creating build/bdist.linux-aarch64/wheel/jetson_stats-4.2.9.data/data
  creating build/bdist.linux-aarch64/wheel/jetson_stats-4.2.9.data/data/jetson_stats
  copying services/jtop.service -> build/bdist.linux-aarch64/wheel/jetson_stats-4.2.9.data/data/jetson_stats
  copying scripts/jtop_env.sh -> build/bdist.linux-aarch64/wheel/jetson_stats-4.2.9.data/data/jetson_stats
  running install_egg_info
  running egg_info
  writing jetson_stats.egg-info/PKG-INFO
  writing dependency_links to jetson_stats.egg-info/dependency_links.txt
  writing entry points to jetson_stats.egg-info/entry_points.txt
  writing requirements to jetson_stats.egg-info/requires.txt
  writing top-level names to jetson_stats.egg-info/top_level.txt
  reading manifest file 'jetson_stats.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files found matching 'Dockerfile'
  warning: no previously-included files found matching '.dockerignore'
  no previously-included directories found matching 'tests'
  no previously-included directories found matching 'docs'
  no previously-included directories found matching 'examples'
  adding license file 'LICENSE'
  writing manifest file 'jetson_stats.egg-info/SOURCES.txt'
  Copying jetson_stats.egg-info to build/bdist.linux-aarch64/wheel/jetson_stats-4.2.9.egg-info
  running install_scripts
  INFO:jtop.core.jetson_variables:Install jtop_env.sh variables
  INFO:jtop.core.jetson_variables: - COPYING jtop_env.sh -> /etc/profile.d/jtop_env.sh
  INFO:jtop.service:Install jtop.service
  INFO:jtop.service: - COPYING jtop.service -> /etc/systemd/system/jtop.service
  INFO:jtop.service: - Reload all daemons
  INFO:jtop.service: - ENABLE jtop.service
  INFO:jtop.service: - START jtop.service
  adding license file "LICENSE" (matched pattern "LICENSE")
  creating build/bdist.linux-aarch64/wheel/jetson_stats-4.2.9.dist-info/WHEEL
  creating '/tmp/pip-wheel-wlt_shy4/jetson_stats-4.2.9-py3-none-any.whl' and adding 'build/bdist.linux-aarch64/wheel' to it
  adding 'jetson_stats-4.2.9.data/data/jetson_stats/jtop.service'
  adding 'jetson_stats-4.2.9.data/data/jetson_stats/jtop_env.sh'
  adding 'jtop/__init__.py'
  adding 'jtop/__main__.py'
  adding 'jtop/github.py'
  adding 'jtop/jetson_config.py'
  adding 'jtop/jetson_release.py'
  adding 'jtop/jetson_swap.py'
  adding 'jtop/jtop.py'
  adding 'jtop/service.py'
  adding 'jtop/terminal_colors.py'
  adding 'jtop/core/__init__.py'
  adding 'jtop/core/command.py'
  adding 'jtop/core/common.py'
  adding 'jtop/core/config.py'
  adding 'jtop/core/cpu.py'
  adding 'jtop/core/engine.py'
  adding 'jtop/core/exceptions.py'
  adding 'jtop/core/fan.py'
  adding 'jtop/core/gpu.py'
  adding 'jtop/core/hardware.py'
  adding 'jtop/core/jetson_clocks.py'
  adding 'jtop/core/jetson_libraries.py'
  adding 'jtop/core/jetson_variables.py'
  adding 'jtop/core/memory.py'
  adding 'jtop/core/nvpmodel.py'
  adding 'jtop/core/power.py'
  adding 'jtop/core/processes.py'
  adding 'jtop/core/tegra_parse.py'
  adding 'jtop/core/tegrastats.py'
  adding 'jtop/core/temperature.py'
  adding 'jtop/core/timer_reader.py'
  adding 'jtop/gui/__init__.py'
  adding 'jtop/gui/jtopgui.py'
  adding 'jtop/gui/jtopguiconfig.py'
  adding 'jtop/gui/pall.py'
  adding 'jtop/gui/pcontrol.py'
  adding 'jtop/gui/pcpu.py'
  adding 'jtop/gui/pengine.py'
  adding 'jtop/gui/pgpu.py'
  adding 'jtop/gui/pinfo.py'
  adding 'jtop/gui/pmem.py'
  adding 'jtop/gui/lib/__init__.py'
  adding 'jtop/gui/lib/chart.py'
  adding 'jtop/gui/lib/colors.py'
  adding 'jtop/gui/lib/common.py'
  adding 'jtop/gui/lib/linear_gauge.py'
  adding 'jtop/gui/lib/process_table.py'
  adding 'jtop/gui/lib/smallbutton.py'
  adding 'jetson_stats-4.2.9.dist-info/LICENSE'
  adding 'jetson_stats-4.2.9.dist-info/METADATA'
  adding 'jetson_stats-4.2.9.dist-info/WHEEL'
  adding 'jetson_stats-4.2.9.dist-info/entry_points.txt'
  adding 'jetson_stats-4.2.9.dist-info/top_level.txt'
  adding 'jetson_stats-4.2.9.dist-info/RECORD'
  removing build/bdist.linux-aarch64/wheel
  Building wheel for jetson-stats (setup.py) ... done
  Created wheel for jetson-stats: filename=jetson_stats-4.2.9-py3-none-any.whl size=155251 sha256=fccd6718ff96011b05c930943ef8611211805b90e00ea2c17a467226bb42013c
  Stored in directory: /tmp/pip-ephem-wheel-cache-ovk7od2y/wheels/b8/68/bf/2ba6de46fe5a7f601ae840db97f43e5681431d1028bde1c9fe
Successfully built jetson-stats
Installing collected packages: jetson-stats
  changing mode of /usr/local/bin/jetson_config to 755
  changing mode of /usr/local/bin/jetson_release to 755
  changing mode of /usr/local/bin/jetson_swap to 755
  changing mode of /usr/local/bin/jtop to 755
Successfully installed jetson-stats-4.2.9
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```
</details>

**Comment by soyszala** [comment]
One more thing:
I was experimenting with the power mode settings and the issue seems related to power modes.

By default my board had the `15W` power mode, which means, that (if I understand correctly), only 4 CPU cores were active out of 8. While this power mode was active, the crash described above always happened.
However, when I changed the power mode to `MAXN` the issue no longer occurred. In this power mode all the CPU cores were active in my case.

<details>
  <summary>Commands to change power modes</summary>
  
  Check current power mode
  ```
  sudo nvpmodel -q
  ```
  Set power mode
  ```
  sudo nvpmodel -m <x>
  ```
  Where `x` is the ID of the power mode, to list available power modes run:
  ```
  sudo nvpmodel -p --verbose
  ```
  
</details>

**Comment by na-tt** [comment]
Experienced the same on an Nvidia Orin NX 16 GB developer kit with Jetpack 5.1.2 (L4T 35.4.1), following soyszala's advice and changing the power mode (which by default was 15W) to MAXN fixed the issue for me as well.

**Comment by kentdotn** [comment]
I believe this problem occurs when some CPUs are offline.
I've fixed it with the following patch:
```diff
--- jtop/gui/pcpu.py     2024-09-10 05:59:46.172062761 +0000
+++ jtop/gui/pcpu.py.fixed       2024-09-10 05:59:27.839832496 +0000
@@ -119,13 +119,14 @@
         except curses.error:
             pass
         # Print info
-        freq = cpu['freq']
-        freq['online'] = cpu['online']
-        freq['name'] = "Frq"
-        try:
-            freq_gauge(stdscr, pos_y + size_h, pos_x, size_w, cpu['freq'])
-        except curses.error:
-            pass
+        if 'freq' in cpu:
+            freq = cpu['freq']
+            freq['online'] = cpu['online']
+            freq['name'] = "Frq"
+            try:
+                freq_gauge(stdscr, pos_y + size_h, pos_x, size_w, cpu['freq'])
+            except curses.error:
+                pass
 
     def draw(self, key, mouse):
         # Screen size
```
Now you can see no 'Frq` gauge for offline CPUs.
<img width="1025" alt="スクリーンショット 2024-09-10 15 01 34" src="https://github.com/user-attachments/assets/cdf90a9b-16e6-497b-b351-dd69e202a38a">

**Comment by savf** [comment]
After the fix has been merged, the issue does no longer exist in jetson-stats 4.2.11. This issue can be closed.

**Comment by rbonghi** [comment]
Thank you for your help! I really appreciate it!

**Comment by kentdotn** [comment]
Great! Thank you!
